apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-l3-ways50
  labels:
    app: stress-ng-l3-ways50
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-ng-l3-ways50
  template:
    metadata:
      labels:
        app: stress-ng-l3-ways50
    spec:
      containers:
      - name: stress-ng
        image: wdhif/stress-ng:latest     # stress-ng ≥0.11.07
        args:
          - "--cache"
          - "1"
          - "--cache-level"
          - "3"
          - "--cache-ways"
          - "4"
          - "--timeout"
          - "60s"
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
