apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-l3
spec:
  replicas: 1                # will be overridden by your script
  selector:
    matchLabels:
      app: ibench-l3
  template:
    metadata:
      labels:
        app: ibench-l3
    spec:
      containers:
      - name: ibench-l3
        image: ibench:latest
        imagePullPolicy: IfNotPresent
        command: ["./l3", "80"]  # stress L3 for 80s
        resources:
          requests:
            cpu: "1"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "64Mi"