apiVersion: batch/v1
kind: Job
metadata:
  name: ibench-membw
spec:
  template:
    metadata:
      labels:
        app: ibench-membw
    spec:
      containers:
      - name: ibench
        image: ibench:latest
        imagePullPolicy: IfNotPresent
        command: ["./memBw", "120"]
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: minikube   # to be overridden in code
  backoffLimit: 0
