apiVersion: batch/v1
kind: Job
metadata:
  name: ibench  # ← will be replaced in code
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: ibench  # ← will be replaced in code
    spec:
      containers:
      - name: ibench
        image: ibench:latest
        imagePullPolicy: IfNotPresent
        command: ["./l3", "120"]  # ← duration replaced in code
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: minikube  # ← will be replaced in code
