apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-l3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibench-l3
  template:
    metadata:
      labels:
        app: ibench-l3
    spec:
      containers:
      - name: ibench-l3
        image: ibench:latest
        imagePullPolicy: IfNotPresent
        command: ["./l3", "120"] 
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
      nodeSelector:
        kubernetes.io/hostname: minikube
