version: '3.8'

services:
  metrics-api:
    build:
      context: ./metrics_api
    ports:
      - "30090:8000"
    volumes:
      - /opt/pcm_metrics:/opt/pcm_metrics:ro
    container_name: metrics-api

  predictor-api:
    build:
      context: ./predictor_api
    ports:
      - "5000:5000"
    environment:
      - METRICS_SERVICE_URL=http://metrics-api:8000/metrics_csv
    container_name: predictor-api
