# baseline-nginx.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-naive
  labels:
    app: nginx-naive
spec:
  replicas: 1  # Will be scaled by the controller
  selector:
    matchLabels:
      app: nginx-naive
  template:
    metadata:
      labels:
        app: nginx-naive
    spec:
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-naive
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
