apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-collector
spec:
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
        assigned-cores: "" # This will be overwritten by node affinity
    spec:
      containers:
      - name: collector
        image: metrics-collector:core-aware
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ASSIGNED_CORES
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['assigned-cores']
        ports:
        - containerPort: 8000
        securityContext:
          privileged: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["minikube"]
              - key: assigned-cores
                operator: In
                values: ["0-2"]
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["minikube-m02"]
              - key: assigned-cores
                operator: In
                values: ["3-5"]