apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metrics-collector
spec:
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      containers:
      - name: collector
        image: metrics-collector:latest
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: ASSIGNED_CORES
          value: "0-2"  # Default, overridden by node affinity
        ports:
        - containerPort: 8000
        securityContext:
          privileged: true              # needed for PCM access
          capabilities:
            add: ["SYS_ADMIN", "IPC_LOCK"]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["minikube"]  # Node1
              - key: ASSIGNED_CORES
                value: "0-2"
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values: ["minikube-m02"]  # Node2
              - key: ASSIGNED_CORES
                value: "3-5"