apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      nodeSelector:
        slo_scheduler: "true"
      containers:
      - name: metrics-collector
        image: metrics-collector:system
        imagePullPolicy: IfNotPresent   # Use local image in Minikube
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DOMAIN_FILTER
          value: "system"
        ports:
        - name: http
          containerPort: 8000
        securityContext:
          privileged: true              # Needed for PCM access
          capabilities:
            add: ["SYS_ADMIN", "IPC_LOCK"]
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
spec:
  selector:
    app: metrics-collector
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  type: ClusterIP
