apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      nodeSelector:
        nginx: "true"           # ensure this pod lands on the node you labeled / the node 2
      containers:
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Expose on a static port (30000-32767)
  selector:
    app: my-nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Manually assign port 30080