apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-with-load
spec:
  replicas: 1  # You can adjust this
  selector:
    matchLabels:
      app: nginx-with-load
  template:
    metadata:
      labels:
        app: nginx-with-load
    spec:
      containers:
      # Main Nginx container
      - name: nginx
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 2
      
      # Sidecar container with load generator
      - name: load-generator
        image: skandyla/wrk:latest
        args:
        - "/bin/sh"
        - "-c"
        - |
          echo "Waiting for Nginx to be ready..."
          while ! nc -z localhost 80; do sleep 1; done
          echo "Starting load test..."
          wrk -t1 -c50 -d60s -L http://localhost/
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"