apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-cpu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibench-cpu
  template:
    metadata:
      labels:
        app: ibench-cpu
    spec:
      containers:
      - name: ibench
        image: ibench:latest
        imagePullPolicy: IfNotPresent
        command: ["./cpu","80"]
        resources:
          requests:
            cpu: "500m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "64Mi"
