apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-membw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibench-membw
  template:
    metadata:
      labels:
        app: ibench-membw
    spec:
      nodeSelector:
        nginx: "true"
      containers:
      - name: membw
        image: ibench:latest
        imagePullPolicy: IfNotPresent
        command: ["./memBw", "60"]
        resources:
          requests:
            cpu: "1"
            memory: "64Mi"
          limits:
            cpu: "1"
            memory: "64Mi"
