apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-membw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibench-membw
  template:
    metadata:
      labels:
        app: ibench-membw
    spec:
      containers:
      - name: membw
        image: ibench:latest
        imagePullPolicy: IfNotPresent
        command: ["./memBw", "260"]
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"
