apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibench-l3
spec:
  replicas: 1                # will be overridden by your script
  selector:
    matchLabels:
      app: ibench-l3
  template:
    metadata:
      labels:
        app: ibench-l3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nginx
                operator: NotIn
                values: ["true"]  # Ensure this pod does not run on nginx nodes
      containers:
      - name: ibench-l3
        image: ibench:latest
        imagePullPolicy: IfNotPresent
        command: ["./l3", "220"]  # stress L3 for 80s
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"  # Adjust memory limits as needed