apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: my-nginx
  type: NodePort
  ports:
    - name: http
      port: 80            # Port exposed inside the cluster
      targetPort: 80      # Port your NGINX containers expose
      nodePort: 30080     # Optional: manually set the external port (between 30000-32767)
