apiVersion: batch/v1
kind: Job
metadata:
  name: wrk2-load
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: wrk2
        image: haydenjeune/wrk2:latest  # small (~6 MB) image containing wrk2 :contentReference[oaicite:0]{index=0}
        args:
          - "-t1"                  # 1 thread
          - "-c50"                 # 50 concurrent connections
          - "-d60s"                # duration 60 seconds
          - "-R50000"              # constant 50 000 requests/sec
          - "-L"                   # record latency histogram / percentiles
          - "http://nginx-service/" 