# predictor-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictor-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictor
  template:
    metadata:
      labels:
        app: predictor
    spec:
      containers:
      - name: predictor
        image: your-registry/predictor-api:v1
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: models
          mountPath: /app/models
      volumes:
      - name: models
        configMap:
          name: model-config

---
apiVersion: v1
kind: Service
metadata:
  name: predictor-service
spec:
  selector:
    app: predictor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000