apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  # If you’ve enabled the kubelet CPU Manager with "static" policy on your nodes,
  # this Pod will be pinned to a dedicated core when you request & limit exactly 1 CPU.
  containers:
  - name: redis
    image: redis:7.0
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 6379
        name: redis
    # disable data persistence (in-memory only)
    args: ["redis-server", "--save", ""]
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
