apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app: redis  # Targets the Redis Pod
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31000  # Manually chosen (30000-32767)