apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:  # Ensures Pod runs only on labeled nodes
        redis: "true"
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: "500m"    # Pinned to 1 core (if using CPU Manager static policy)
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: NodePort
  selector:
    app: redis  # Targets the Redis Pod
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 31000  # Manually chosen (30000-32767)